name: Validate Python

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install networkx numpy pytest matplotlib pandas
    - name: Run pytest
      run: pytest -v
    - name: Run Python framework
      run: python -m src.icq_pnp.computational_dichotomy --n 100 200 300
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: ic-sat-results
        path: results/
        if-no-files-found: warn
