name: Validate Lean 4 Proofs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Lean 4
      run: |
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
    - name: Install Mathlib
      run: lake update && lake exe cache get mathlib
    - name: Build Lean project
      run: lake build
